# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
  clients:
    default: { url: '%env(ELASTICSEARCH_URL)%' }
  indexes:
    set:
      settings:
        index:
          analysis:
            analyzer:
              name_analyzer:
                type: custom
                tokenizer: nGram
                filter:  [lowercase,stopwords]
              id_analyzer:
                type: custom
                tokenizer: edge_ngram
            tokenizer:
              nGram:
                type:     nGram
                min_gram: 3
                max_gram: 4
              edge_ngram:
                type:     edge_ngram
                min:gram: 3
                max_gram: 10
            filter:
              snowball:
                type: snowball
                language: English
              stopwords:
                type:      stop
                stopwords: [_english_]
                ignore_case: true
      types:
        set:
          properties:
            id:
              type: "keyword"
              fields:
                ngrams:
                  type: 'text'
                  analyzer: id_analyzer
            name: { analyzer: name_analyzer, search_analyzer: "standard" }
            year: { type: integer }
            partCount: { type: integer }
            disabled: { type: boolean }
            completeness: { type: integer }
            theme:
              type: "object"
              properties:
                id: ~
                name: { analyzer: name_analyzer, search_analyzer: "standard"  }
          persistence:
            driver: orm
            model: App\Entity\Rebrickable\Set
            provider: ~
            finder: ~
            repository: App\Repository\Search\SetRepository
            listener:
              insert: true
              update: true
              delete: true

    models:
      settings:
        index:
          analysis:
            analyzer:
              name_analyzer:
                type: custom
                tokenizer: nGram
                filter:  [lowercase,stopwords]
              id_analyzer:
                type: custom
                tokenizer: edge_ngram
            tokenizer:
              nGram:
                type:     nGram
                min_gram: 3
                max_gram: 4
              edge_ngram:
                type:     edge_ngram
                min:gram: 3
                max_gram: 10
            filter:
              snowball:
                type: snowball
                language: English
              stopwords:
                type:      stop
                stopwords: [_english_]
                ignore_case: true
      types:
        model:
          properties:
            id:
              type: "keyword"
              fields:
                ngrams:
                  type: 'text'
                  analyzer: id_analyzer
            name: { analyzer: name_analyzer, search_analyzer: "standard"  }
            #            parents:
            #              type: "object"
            #              properties:
            #                id: { analyzer: id_analyzer, search_analyzer: "standard" }
            category:
              type: "object"
              properties:
                id: ~
                name: { analyzer: name_analyzer, search_analyzer: "standard"  }
            keywords:
              type: "object"
              properties:
                name: { analyzer: name_analyzer, search_analyzer: "standard"  }
            type: { type: text }
          persistence:
            driver: orm
            model: App\Entity\LDraw\Model
            provider: ~
            finder: ~
            repository: App\Repository\Search\ModelRepository
            listener:
              insert: true
              update: true
              delete: true