# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
  clients:
    default: { url: '%env(ELASTICSEARCH_URL)%' }
  index_templates:
    printabrick:
      client: default
      template: printabrick_*
      settings:
        number_of_shards: 1
        number_of_replicas: 0
        index:
          analysis:
            analyzer:
              name_autocomplete:
                tokenizer: whitespace
                filter:
                  - lowercase
                  - edge_ngram
              name_analyzer:
                tokenizer: whitespace
                filter:
                  - lowercase
                  - stopwords
                  - stemmer
                  - stopwords
              id_analyzer:
                type: custom
                tokenizer: id_edge_ngram
                filter:
                  - lowercase
            tokenizer:
              id_edge_ngram:
                type: edge_ngram
                min_gram: 2
                max_gram: 20
            filter:
              edge_ngram:
                type: edge_ngram
                min_gram: 2
                max_gram: 20
              stopwords:
                type: stop
                stopwords: [ _english_ ]
                ignore_case: true
  indexes:
    printabrick_sets:
      properties:
        id:
          type: text
          analyzer: id_analyzer
          search_analyzer: keyword
        name:
          search_analyzer: name_analyzer
          analyzer: name_autocomplete
          boost: 2.0
        year: { type: integer }
        partCount: { type: integer }
        disabled: { type: boolean }
        completeness: { type: integer }
        theme:
          type: object
          properties:
            id: ~
            name: { search_analyzer: name_analyzer, analyzer: name_autocomplete }
      persistence:
        driver: orm
        model: App\Entity\Rebrickable\Set
        repository: App\Repository\Search\SetRepository
        listener:
          insert: false
          update: false
          delete: false

    printabrick_models:
      properties:
        id:
          type: text
          analyzer: id_analyzer
          search_analyzer: keyword
        name:
          search_analyzer: name_analyzer
          analyzer: name_autocomplete
          boost: 2.0
        category:
          type: object
          properties:
            id: ~
            name:
              type: keyword
        keywords:
          type: object
          properties:
            name: { search_analyzer: name_analyzer, analyzer: name_autocomplete }
        type:
          type: object
          properties:
            name:
              type: keyword

      persistence:
        driver: orm
        model: App\Entity\LDraw\Model
        repository: App\Repository\Search\ModelRepository
        listener:
          insert: false
          update: false
          delete: false