# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        media:
            local:
                directory: "%app.media_root%"
    filesystems:
        media:
            adapter: media