twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['form/semantic-ui.html.twig', 'form/search.html.twig']
    globals:
        name: "%name%"
