imports:
    - { resource: service/legacy_aliases.yml }
    - { resource: service/front.yml }
    - { resource: service/loader.yml }

services:
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        public: false
        bind:
            $bricksetApiKey: '%brickset_apikey%'
            $rebrickableApiKey: '%rebrickable_apikey%'

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Exception}'

    app.relations.cache_provider:
        class: Doctrine\Common\Cache\ArrayCache

    app.brickset.cache_provider:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments: ["%kernel.cache_dir%/brickset", ".cache.php"]

    AppBundle\Api\Manager\RebrickableManager: ~

    AppBundle\Api\Manager\BricksetManager:
        arguments:
           $cache: '@app.brickset.cache_provider'


    # Filesystem

    League\Flysystem\FilesystemInterface:
        alias: oneup_flysystem.media_filesystem


    # ElasticSearch

    FOS\ElasticaBundle\Manager\RepositoryManagerInterface:
        alias: fos_elastica.repository_manager

    AppBundle\Service\SearchService:
        arguments:
            - '@fos_elastica.manager'